[2025-01-31 20:44:44,830] app INFO - http://127.0.0.1:5000/: Requested
[2025-01-31 20:44:44,830] app INFO - http://127.0.0.1:5000/: Completed
[2025-01-31 20:44:44,888] app INFO - http://127.0.0.1:5000/favicon.ico: Requested
[2025-01-31 20:44:44,888] app INFO - http://127.0.0.1:5000/favicon.ico: Completed
[2025-01-31 20:45:17,473] app INFO - http://127.0.0.1:5000/swagger: Requested
[2025-01-31 20:45:17,473] app INFO - http://127.0.0.1:5000/swagger: Completed
[2025-01-31 20:45:17,481] app INFO - http://127.0.0.1:5000/swagger/: Requested
[2025-01-31 20:45:17,504] app INFO - http://127.0.0.1:5000/swagger/: Completed
[2025-01-31 20:45:17,694] app INFO - http://127.0.0.1:5000/swaggerui/droid-sans.css: Requested
[2025-01-31 20:45:17,698] app INFO - http://127.0.0.1:5000/swaggerui/droid-sans.css: Completed
[2025-01-31 20:45:17,713] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui.css: Requested
[2025-01-31 20:45:17,714] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui.css: Completed
[2025-01-31 20:45:17,714] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui-bundle.js: Requested
[2025-01-31 20:45:17,715] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui-bundle.js: Completed
[2025-01-31 20:45:17,741] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui-standalone-preset.js: Requested
[2025-01-31 20:45:17,742] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui-standalone-preset.js: Completed
[2025-01-31 20:45:18,050] app INFO - http://127.0.0.1:5000/swagger.json: Requested
[2025-01-31 20:45:18,050] app INFO - http://127.0.0.1:5000/swagger.json: Completed
[2025-01-31 20:45:18,117] app INFO - http://127.0.0.1:5000/swaggerui/favicon-32x32.png: Requested
[2025-01-31 20:45:18,118] app INFO - http://127.0.0.1:5000/swaggerui/favicon-32x32.png: Completed
[2025-02-01 12:33:34,784] app INFO - http://127.0.0.1:5000/: Requested
[2025-02-01 12:33:34,787] app INFO - http://127.0.0.1:5000/: Completed
[2025-02-01 12:33:34,845] app INFO - http://127.0.0.1:5000/favicon.ico: Requested
[2025-02-01 12:33:34,846] app INFO - http://127.0.0.1:5000/favicon.ico: Completed
[2025-02-01 12:33:37,423] app INFO - http://127.0.0.1:5000/swagger/: Requested
[2025-02-01 12:33:37,441] app INFO - http://127.0.0.1:5000/swagger/: Completed
[2025-02-01 12:33:37,468] app INFO - http://127.0.0.1:5000/swaggerui/droid-sans.css: Requested
[2025-02-01 12:33:37,472] app INFO - http://127.0.0.1:5000/swaggerui/droid-sans.css: Completed
[2025-02-01 12:33:37,638] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui.css: Requested
[2025-02-01 12:33:37,639] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui.css: Completed
[2025-02-01 12:33:37,653] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui-bundle.js: Requested
[2025-02-01 12:33:37,654] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui-bundle.js: Completed
[2025-02-01 12:33:37,687] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui-standalone-preset.js: Requested
[2025-02-01 12:33:37,688] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui-standalone-preset.js: Completed
[2025-02-01 12:33:38,027] app INFO - http://127.0.0.1:5000/swagger.json: Requested
[2025-02-01 12:33:38,027] app INFO - http://127.0.0.1:5000/swagger.json: Completed
[2025-02-01 12:33:38,058] app INFO - http://127.0.0.1:5000/swaggerui/favicon-32x32.png: Requested
[2025-02-01 12:33:38,059] app INFO - http://127.0.0.1:5000/swaggerui/favicon-32x32.png: Completed
[2025-02-01 12:39:39,601] app INFO - http://127.0.0.1:5000/: Requested
[2025-02-01 12:39:39,602] app INFO - http://127.0.0.1:5000/: Completed
[2025-02-01 12:39:42,619] app INFO - http://127.0.0.1:5000/swagger/: Requested
[2025-02-01 12:39:42,641] app INFO - http://127.0.0.1:5000/swagger/: Completed
[2025-02-01 12:39:42,763] app INFO - http://127.0.0.1:5000/swaggerui/droid-sans.css: Requested
[2025-02-01 12:39:42,767] app INFO - http://127.0.0.1:5000/swaggerui/droid-sans.css: Completed
[2025-02-01 12:39:42,794] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui.css: Requested
[2025-02-01 12:39:42,795] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui.css: Completed
[2025-02-01 12:39:42,816] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui-bundle.js: Requested
[2025-02-01 12:39:42,816] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui-bundle.js: Completed
[2025-02-01 12:39:42,849] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui-standalone-preset.js: Requested
[2025-02-01 12:39:42,850] app INFO - http://127.0.0.1:5000/swaggerui/swagger-ui-standalone-preset.js: Completed
[2025-02-01 12:39:43,190] app INFO - http://127.0.0.1:5000/swagger.json: Requested
[2025-02-01 12:39:43,191] app INFO - http://127.0.0.1:5000/swagger.json: Completed
[2025-02-01 12:39:46,070] app INFO - http://127.0.0.1:5000/swagger.json: Requested
[2025-02-01 12:39:46,070] app INFO - http://127.0.0.1:5000/swagger.json: Completed
[2025-02-01 13:13:33,793] app INFO - http://127.0.0.1:5000/: Requested
[2025-02-01 13:13:33,794] app ERROR - http://127.0.0.1:5000/: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/api.py", line 446, in render_root
    self.abort(HTTPStatus.NOT_FOUND)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/namespace.py", line 153, in abort
    abort(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/errors.py", line 28, in abort
    flask.abort(code)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/helpers.py", line 272, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-01 13:13:33,800] app INFO - http://127.0.0.1:5000/: Erro que eu nao sei
[2025-02-01 13:13:33,801] app INFO - http://127.0.0.1:5000/: Completed
[2025-02-01 13:13:36,327] app INFO - http://127.0.0.1:5000/swagger/: Requested
[2025-02-01 13:13:36,328] app ERROR - http://127.0.0.1:5000/swagger/: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-01 13:13:36,334] app INFO - http://127.0.0.1:5000/swagger/: Erro que eu nao sei
[2025-02-01 13:13:36,335] app INFO - http://127.0.0.1:5000/swagger/: Completed
[2025-02-01 13:13:41,712] app INFO - http://127.0.0.1:5000/swagger/: Requested
[2025-02-01 13:13:41,712] app ERROR - http://127.0.0.1:5000/swagger/: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-01 13:13:41,713] app INFO - http://127.0.0.1:5000/swagger/: Erro que eu nao sei
[2025-02-01 13:13:41,713] app INFO - http://127.0.0.1:5000/swagger/: Completed
[2025-02-01 13:13:42,542] app INFO - http://127.0.0.1:5000/swagger/: Requested
[2025-02-01 13:13:42,543] app ERROR - http://127.0.0.1:5000/swagger/: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-01 13:13:42,545] app INFO - http://127.0.0.1:5000/swagger/: Erro que eu nao sei
[2025-02-01 13:13:42,545] app INFO - http://127.0.0.1:5000/swagger/: Completed
[2025-02-01 13:13:42,915] app INFO - http://127.0.0.1:5000/swagger/: Requested
[2025-02-01 13:13:42,916] app ERROR - http://127.0.0.1:5000/swagger/: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-01 13:13:42,918] app INFO - http://127.0.0.1:5000/swagger/: Erro que eu nao sei
[2025-02-01 13:13:42,918] app INFO - http://127.0.0.1:5000/swagger/: Completed
[2025-02-01 13:13:43,110] app INFO - http://127.0.0.1:5000/swagger/: Requested
[2025-02-01 13:13:43,110] app ERROR - http://127.0.0.1:5000/swagger/: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-01 13:13:43,111] app INFO - http://127.0.0.1:5000/swagger/: Erro que eu nao sei
[2025-02-01 13:13:43,111] app INFO - http://127.0.0.1:5000/swagger/: Completed
[2025-02-01 13:13:54,480] app INFO - http://127.0.0.1:5000/: Requested
[2025-02-01 13:13:54,480] app ERROR - http://127.0.0.1:5000/: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/api.py", line 446, in render_root
    self.abort(HTTPStatus.NOT_FOUND)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/namespace.py", line 153, in abort
    abort(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/errors.py", line 28, in abort
    flask.abort(code)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/helpers.py", line 272, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-01 13:13:54,481] app INFO - http://127.0.0.1:5000/: Erro que eu nao sei
[2025-02-01 13:13:54,481] app INFO - http://127.0.0.1:5000/: Completed
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:workspace.app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/api.py", line 446, in render_root
    self.abort(HTTPStatus.NOT_FOUND)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/namespace.py", line 153, in abort
    abort(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/errors.py", line 28, in abort
    flask.abort(code)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/helpers.py", line 272, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [01/Feb/2025 13:14:29] "[33mGET / HTTP/1.1[0m" 404 -
ERROR:workspace.app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/api.py", line 446, in render_root
    self.abort(HTTPStatus.NOT_FOUND)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/namespace.py", line 153, in abort
    abort(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/errors.py", line 28, in abort
    flask.abort(code)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/helpers.py", line 272, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [01/Feb/2025 13:14:29] "[33mGET / HTTP/1.1[0m" 404 -
ERROR:workspace.app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/api.py", line 446, in render_root
    self.abort(HTTPStatus.NOT_FOUND)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/namespace.py", line 153, in abort
    abort(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/errors.py", line 28, in abort
    flask.abort(code)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/helpers.py", line 272, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [01/Feb/2025 13:14:29] "[33mGET / HTTP/1.1[0m" 404 -
ERROR:workspace.app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/api.py", line 446, in render_root
    self.abort(HTTPStatus.NOT_FOUND)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/namespace.py", line 153, in abort
    abort(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/errors.py", line 28, in abort
    flask.abort(code)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/helpers.py", line 272, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [01/Feb/2025 13:14:30] "[33mGET / HTTP/1.1[0m" 404 -
ERROR:workspace.app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/api.py", line 446, in render_root
    self.abort(HTTPStatus.NOT_FOUND)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/namespace.py", line 153, in abort
    abort(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/errors.py", line 28, in abort
    flask.abort(code)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/helpers.py", line 272, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [01/Feb/2025 13:14:30] "[33mGET / HTTP/1.1[0m" 404 -
ERROR:workspace.app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/api.py", line 446, in render_root
    self.abort(HTTPStatus.NOT_FOUND)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/namespace.py", line 153, in abort
    abort(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/errors.py", line 28, in abort
    flask.abort(code)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/helpers.py", line 272, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [01/Feb/2025 13:14:30] "[33mGET / HTTP/1.1[0m" 404 -
ERROR:workspace.app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [01/Feb/2025 13:14:31] "[33mGET /swagger/ HTTP/1.1[0m" 404 -
ERROR:workspace.app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
INFO:werkzeug:127.0.0.1 - - [01/Feb/2025 13:14:32] "[33mGET /swagger/ HTTP/1.1[0m" 404 -
[2025-02-01 13:14:48,875] app INFO - http://127.0.0.1:5000/swagger/: Requested
[2025-02-01 13:14:48,876] app ERROR - http://127.0.0.1:5000/swagger/: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-01 13:14:48,877] app INFO - http://127.0.0.1:5000/swagger/: Erro que eu nao sei
[2025-02-01 13:14:48,877] app INFO - http://127.0.0.1:5000/swagger/: Completed
[2025-02-01 13:14:50,340] app INFO - http://127.0.0.1:5000/swagger/: Requested
[2025-02-01 13:14:50,341] app ERROR - http://127.0.0.1:5000/swagger/: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-01 13:14:50,343] app INFO - http://127.0.0.1:5000/swagger/: Erro que eu nao sei
[2025-02-01 13:14:50,343] app INFO - http://127.0.0.1:5000/swagger/: Completed
[2025-02-01 13:16:40,498] app INFO - http://127.0.0.1:5000/: Requested
[2025-02-01 13:16:40,499] app ERROR - http://127.0.0.1:5000/: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/api.py", line 446, in render_root
    self.abort(HTTPStatus.NOT_FOUND)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/namespace.py", line 153, in abort
    abort(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/errors.py", line 28, in abort
    flask.abort(code)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/helpers.py", line 272, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-01 13:16:40,503] app INFO - http://127.0.0.1:5000/: Erro que eu nao sei
[2025-02-01 13:16:40,503] app INFO - http://127.0.0.1:5000/: Completed
[2025-02-01 13:16:42,853] app INFO - http://127.0.0.1:5000/swagger/: Requested
[2025-02-01 13:16:42,854] app ERROR - http://127.0.0.1:5000/swagger/: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-01 13:16:42,856] app INFO - http://127.0.0.1:5000/swagger/: Erro que eu nao sei
[2025-02-01 13:16:42,857] app INFO - http://127.0.0.1:5000/swagger/: Completed
[2025-02-01 13:16:43,500] app INFO - http://127.0.0.1:5000/swagger/: Requested
[2025-02-01 13:16:43,501] app ERROR - http://127.0.0.1:5000/swagger/: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-01 13:16:43,503] app INFO - http://127.0.0.1:5000/swagger/: Erro que eu nao sei
[2025-02-01 13:16:43,503] app INFO - http://127.0.0.1:5000/swagger/: Completed
[2025-02-01 13:19:03,302] app INFO - http://localhost:5000/swagger: Requested
[2025-02-01 13:19:03,313] app INFO - http://localhost:5000/swagger: Completed
[2025-02-01 13:19:03,394] app INFO - http://localhost:5000/swaggerui/droid-sans.css: Requested
[2025-02-01 13:19:03,400] app INFO - http://localhost:5000/swaggerui/droid-sans.css: Completed
[2025-02-01 13:19:03,514] app INFO - http://localhost:5000/swaggerui/swagger-ui.css: Requested
[2025-02-01 13:19:03,515] app INFO - http://localhost:5000/swaggerui/swagger-ui.css: Completed
[2025-02-01 13:19:03,522] app INFO - http://localhost:5000/swaggerui/swagger-ui-bundle.js: Requested
[2025-02-01 13:19:03,522] app INFO - http://localhost:5000/swaggerui/swagger-ui-bundle.js: Completed
[2025-02-01 13:19:03,548] app INFO - http://localhost:5000/swaggerui/swagger-ui-standalone-preset.js: Requested
[2025-02-01 13:19:03,549] app INFO - http://localhost:5000/swaggerui/swagger-ui-standalone-preset.js: Completed
[2025-02-01 13:19:03,880] app INFO - http://localhost:5000/swagger.json: Requested
[2025-02-01 13:19:03,882] app INFO - http://localhost:5000/swagger.json: Completed
[2025-02-01 13:19:03,885] app INFO - http://localhost:5000/swaggerui/favicon-32x32.png: Requested
[2025-02-01 13:19:03,886] app INFO - http://localhost:5000/swaggerui/favicon-32x32.png: Completed
[2025-02-01 13:19:41,440] app INFO - http://localhost:5000/api/users/: Requested
[2025-02-01 13:19:41,447] app INFO - http://localhost:5000/api/users/: Completed
[2025-02-01 13:20:26,589] app INFO - http://localhost:5000/api/users/: Requested
[2025-02-01 13:20:26,594] app ERROR - http://localhost:5000/api/users/: Exception on /api/users/ [POST]
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/api.py", line 402, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/resource.py", line 41, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/workspace/controllers/userController.py", line 44, in post
    preference_auto_update_panel_items=data["preference_auto_update_panel_items"],
                                       ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'preference_auto_update_panel_items'
[2025-02-01 13:20:26,602] app INFO - http://localhost:5000/api/users/: Completed
[2025-02-01 13:21:11,395] app INFO - http://localhost:5000/api/users/: Requested
[2025-02-01 13:21:11,396] app INFO - http://localhost:5000/api/users/: Completed
[2025-02-01 13:21:18,209] app INFO - http://localhost:5000/api/users/: Requested
[2025-02-01 13:21:18,210] app INFO - http://localhost:5000/api/users/: Completed
[2025-02-01 18:37:46,777] app INFO - http://127.0.0.1:5000/: Requested
[2025-02-01 18:37:46,778] app ERROR - http://127.0.0.1:5000/: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/api.py", line 446, in render_root
    self.abort(HTTPStatus.NOT_FOUND)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/namespace.py", line 153, in abort
    abort(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask_restx/errors.py", line 28, in abort
    flask.abort(code)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/helpers.py", line 272, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-01 18:37:46,780] app INFO - http://127.0.0.1:5000/: Erro que eu nao sei
[2025-02-01 18:37:46,780] app INFO - http://127.0.0.1:5000/: Completed
[2025-02-01 18:37:46,818] app INFO - http://127.0.0.1:5000/favicon.ico: Requested
[2025-02-01 18:37:46,818] app ERROR - http://127.0.0.1:5000/favicon.ico: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-01 18:37:46,822] app INFO - http://127.0.0.1:5000/favicon.ico: Erro que eu nao sei
[2025-02-01 18:37:46,822] app INFO - http://127.0.0.1:5000/favicon.ico: Completed
[2025-02-01 18:37:49,322] app INFO - http://127.0.0.1:5000/swagger/: Requested
[2025-02-01 18:37:49,322] app ERROR - http://127.0.0.1:5000/swagger/: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-01 18:37:49,323] app INFO - http://127.0.0.1:5000/swagger/: Erro que eu nao sei
[2025-02-01 18:37:49,323] app INFO - http://127.0.0.1:5000/swagger/: Completed
[2025-02-01 18:37:49,923] app INFO - http://127.0.0.1:5000/swagger/: Requested
[2025-02-01 18:37:49,923] app ERROR - http://127.0.0.1:5000/swagger/: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-02-01 18:37:49,924] app INFO - http://127.0.0.1:5000/swagger/: Erro que eu nao sei
[2025-02-01 18:37:49,924] app INFO - http://127.0.0.1:5000/swagger/: Completed
[2025-02-01 18:37:52,221] app INFO - http://localhost:5000/swagger: Requested
[2025-02-01 18:37:52,257] app INFO - http://localhost:5000/swagger: Completed
[2025-02-01 18:37:52,323] app INFO - http://localhost:5000/swaggerui/droid-sans.css: Requested
[2025-02-01 18:37:52,329] app INFO - http://localhost:5000/swaggerui/droid-sans.css: Completed
[2025-02-01 18:37:52,448] app INFO - http://localhost:5000/swaggerui/swagger-ui.css: Requested
[2025-02-01 18:37:52,448] app INFO - http://localhost:5000/swaggerui/swagger-ui.css: Completed
[2025-02-01 18:37:52,460] app INFO - http://localhost:5000/swaggerui/swagger-ui-bundle.js: Requested
[2025-02-01 18:37:52,461] app INFO - http://localhost:5000/swaggerui/swagger-ui-bundle.js: Completed
[2025-02-01 18:37:52,484] app INFO - http://localhost:5000/swaggerui/swagger-ui-standalone-preset.js: Requested
[2025-02-01 18:37:52,485] app INFO - http://localhost:5000/swaggerui/swagger-ui-standalone-preset.js: Completed
[2025-02-01 18:37:52,688] app INFO - http://localhost:5000/swagger.json: Requested
[2025-02-01 18:37:52,693] app INFO - http://localhost:5000/swagger.json: Completed
[2025-02-01 18:37:52,699] app INFO - http://localhost:5000/swaggerui/favicon-32x32.png: Requested
[2025-02-01 18:37:52,700] app INFO - http://localhost:5000/swaggerui/favicon-32x32.png: Completed
[2025-02-01 18:37:57,826] app INFO - http://localhost:5000/api/users/: Requested
[2025-02-01 18:37:57,836] app INFO - http://localhost:5000/api/users/: Completed
[2025-02-01 18:38:15,259] app INFO - http://localhost:5000/api/users/: Requested
[2025-02-01 18:38:15,261] app INFO - http://localhost:5000/api/users/: Completed
[2025-02-01 18:38:29,428] app INFO - http://localhost:5000/api/users/1: Requested
[2025-02-01 18:38:29,433] app INFO - http://localhost:5000/api/users/1: Completed
[2025-02-01 18:38:32,891] app INFO - http://localhost:5000/api/users/21: Requested
[2025-02-01 18:38:32,893] app INFO - http://localhost:5000/api/users/21: Completed
[2025-02-01 18:48:21,346] app INFO - http://localhost:5000/swagger: Requested
[2025-02-01 18:48:21,372] app INFO - http://localhost:5000/swagger: Completed
[2025-02-01 18:48:21,429] app INFO - http://localhost:5000/swaggerui/droid-sans.css: Requested
[2025-02-01 18:48:21,434] app INFO - http://localhost:5000/swaggerui/droid-sans.css: Completed
[2025-02-01 18:48:21,552] app INFO - http://localhost:5000/swaggerui/swagger-ui.css: Requested
[2025-02-01 18:48:21,553] app INFO - http://localhost:5000/swaggerui/swagger-ui.css: Completed
[2025-02-01 18:48:21,557] app INFO - http://localhost:5000/swaggerui/swagger-ui-bundle.js: Requested
[2025-02-01 18:48:21,557] app INFO - http://localhost:5000/swaggerui/swagger-ui-bundle.js: Completed
[2025-02-01 18:48:21,584] app INFO - http://localhost:5000/swaggerui/swagger-ui-standalone-preset.js: Requested
[2025-02-01 18:48:21,585] app INFO - http://localhost:5000/swaggerui/swagger-ui-standalone-preset.js: Completed
[2025-02-01 18:48:21,812] app INFO - http://localhost:5000/swaggerui/favicon-32x32.png: Requested
[2025-02-01 18:48:21,813] app INFO - http://localhost:5000/swaggerui/favicon-32x32.png: Completed
[2025-02-01 18:48:21,852] app INFO - http://localhost:5000/swagger.json: Requested
[2025-02-01 18:48:21,857] app INFO - http://localhost:5000/swagger.json: Completed
[2025-02-01 18:48:45,685] app INFO - http://localhost:5000/api/users/: Requested
